services:
  db:
    container_name: wayffs-db-prod
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    networks:
      - wayffs-network

  backend:
    container_name: wayffs-backend-prod
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=wayffs-api.edioq.com localhost 127.0.0.1
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=5432
      - CORS_ALLOWED_ORIGINS=https://wayffs.vercel.app,https://edioq.com,https://www.edioq.com
      - CSRF_TRUSTED_ORIGINS=https://wayffs-api.edioq.com
    depends_on:
      - db
    networks:
      - wayffs-network

  nginx:
    container_name: wayffs-nginx-prod
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - backend
    networks:
      - wayffs-network

volumes:
  postgres_data:
  static_volume:


networks:
  wayffs-network:
    driver: bridge
