services:
  db:
    container_name: wayffs-db-prod
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    networks:
      - wayffs-network

  backend:
    container_name: wayffs-backend-prod
    build: ./backend
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=5432
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT}
    depends_on:
      - db
    networks:
      - wayffs-network

  nginx:
    container_name: wayffs-nginx-prod
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - static_volume:/app/staticfiles
    environment:
      - API_DOMAIN=${API_DOMAIN}
    depends_on:
      - backend
    networks:
      - wayffs-network

volumes:
  postgres_data:
  static_volume:


networks:
  wayffs-network:
    driver: bridge
